### ISSUE TITLE
It would be really nice to have a dark FlatUI theme as well

### ISSUE THREAD

**Issue by TravisBarryDick** [MetroWind/emacs-flatui-theme#1]
Hey, thanks for the nice theme!

It would be really nice to also have a dark theme based on the FlatUI color scheme (maybe something like this theme for Terminal.app: https://dribbble.com/shots/1021755-Flat-UI-Terminal-Theme). I tried my hand at doing it myself, but I didn't have much luck.

Thanks again!
Travis

**Comment by dotmilk** [comment]
Any hope for this?
